import React from "react";
import styles from "@/app/page.module.css";
import Image from "next/image";
import Button from "./../../components/Button/Button";

export const metadata = {
  title: "Contact",
  description: "Generated by Ulas Iron",
};

const Contact = () => {
  return (
    <div className={styles.contact}>
      <div className={styles.titleContainer}>
        <h1 className={styles.contactTitle}>Lets keep in touch</h1>
      </div>
      <div className={styles.bottomContainer}>
        <div className={styles.contactImg}>
          <Image src="/contact.png" alt="contact" width={400} height={400} />
        </div>

        <form className={styles.form}>
          <input
            type="email"
            name="email"
            id="email"
            placeholder="email"
            className={styles.input}
          />
          <input
            type="password"
            name="password"
            id="password"
            placeholder="password"
            className={styles.input}
          />
          <textarea
            className={styles.textArea}
            cols="30"
            rows="10"
            placeholder="Message"
          ></textarea>
          <Button url="#" text="Send" />
        </form>
      </div>
    </div>
  );
};

export default Contact;
